
# ZenthronBot - Bot texts
# Copyright (C) 2025 R0X
# Licensed under the GNU General Public License v3.0
# See the LICENSE file for details.

# --- ACTION COMMANDS TEXTS ---

KILL_TEXTS = [
    "Unleashed a script of fury upon {target}. They have been *deleted*. ☠️ R.I.P.",
    "Executed the forbidden 'force_delete' protocol on {target}. They won't be bothering this chat again. 👻",
    "{target} has been permanently relocated to the '/dev/null' zone.",
    "The access control list has spoken! {target} is hereby banished from this chat. 🚫 Begone!",
    "{target} made the fatal error of triggering a restricted process. The punishment is... *eternal silence*. Effective immediately. 🤫",
    "Consider {target} thoroughly disintegrated and removed from the premises. 💨",
    "The admin council has voted unanimously. {target} is OUT! 🗳️",
    "Executed a precision tactical strike—{target} no longer exists within this chat. Mission accomplished. 💥",
    "Marked {target} for immediate deletion... process initiated via intense, disapproving code. ❌",
    "Declared administrative action upon {target}. Victory was swift and decisive. Flag captured! 🚩",
    "Delivered a final, decisive 'remove user' command—{target} is now officially relegated to the logs.",
    "Launched a devastating revenge assault. {target} is no more. Vengeance is complete! 😠",
    "Transferred {target} to the Shadow Realm (also known as the 'Ignored Users List').",
    "Ruthlessly removed {target}'s name from the 'Approved User' list. Permanently. No appeal possible. 📝❌",
    "One swift, dismissive command and {target} was obliterated into a thousand bits of dust. ✨",
    "{target} flagrantly crossed an invisible, yet sacred, line. Now only silence remains.",
    "I came. I saw. I conquered. {target} has been vanquished. Kneel before my might! 🏆",
    "{target} committed an unforgivable error. This is their downfall.",
    "Proclaimed myself undisputed ruler of this domain. {target} foolishly refused to comply. They have now been dethroned and exiled.",
    "The system logs foretold this very day... the day of {target}'s inevitable downfall. The scripts were right! 📜",
    "There can be only one. {target} has been ceremonially removed.",
    "Fired the concentrated laser beam of 'ignore'. {target} has been vaporized from my attention span.",
    "{target}'s continued presence has been reviewed and deemed... unnecessary. *poof* Gone.",
    "Dispatched {target} with extreme prejudice to the Land of Wind and Ghosts. Farewell.",
    "Mathematically erased {target} from the social equation. Problem solved. Q.E.D.",
    "The mighty 'delete' command has struck {target} with unerring accuracy! User not found. ❌",
    "{target} has ceased to be relevant. Their significance level has dropped below zero.",
    "My judgment is swift, merciless, and final. {target} is hereby declared... irrelevant. Next!",
    "Consider {target} yeeted into the cosmic abyss with considerable force. Have a nice trip! 👋🌌",
    "Activated the impenetrable Cloak of Ignoring. {target} is now invisible and nonexistent to me.",
    "Dropped the legendary Ban Hammer squarely upon {target}. 🔨💥",
    "Poof! Abracadabra! {target} has been transformed into digital dust.",
    "Executed `rm -rf {target}`.",
    "Blocked {target} with extreme prejudice.",
    "Unsubscribed from {target}'s nonsense.",
    "Muted {target} indefinitely.",
    "Archived {target} into oblivion.",
    "{target} has been ghosted.",
]

PUNCH_TEXTS = [
    "Delivered a swift, calculated punch directly to {target}! Sent 'em flying across the chat! 🥊💨",
    "{target} got too close to a restricted area. A stern warning punch was administered. Back off! 👊",
    "A quick, decisive 'thump!' sends {target} tumbling out of the conversation! 👋💥",
    "My fist connected squarely with {target}'s avatar. Message delivered: Vacate the premises. 💬",
    "{target} learned the hard way not to cross the line. Lesson delivered! <i>*Punch!*</i>",
    "Ejected {target} with extreme prejudice and a mighty punch. Get out! 🚀",
    "One well-aimed punch was all it took. Bye bye, {target}! 👋",
    "Hit {target} with the classic ol' one-two combo! Jab! Cross! Down goes {target}! 💥",
    "Served {target} a knuckle sandwich. Extra salt. Enjoy! 🥪",
    "Pow! Right in the kisser, {target}! 😘➡️💥",
    "Administered a concentrated dose of Power Punch™ to {target}! 💪",
    "This punch is rated 'E' for 'Effective' at removing {target} from my sight.",
    "{target} got knocked down for the count! The referee waves it off! Ding ding ding! 🔔",
    "Sent {target} packing with a haymaker that shook the room! 💨",
    "BAM! KAPOW! {target} felt that impact right through their ego!",
    "Launched a fist of fury directly at {target}. Target down.",
    "Consider {target} TKO'd! Throw in the towel!",
    "Whammo! A direct hit right to {target}'s smug comment!",
    "Delivered a power punch to {target}. Hope it stung.",
    "Eat canvas, {target}! You're down!",
    "That's a definitive knockout blow landed squarely on {target}!",
    "My virtual fists are lightning-fast. {target} just got the full combo.",
    "Sending {target} a devastating uppercut! Right on the chin!",
    "FALCON PUNCH! Executed perfectly on {target}!",
    "Hit {target} with a rapid-fire flurry of jabs! Duck and weave!",
    "A sneaky southpaw punch! {target} never saw it coming!",
    "Pow! Zok! Biff! Whack! {target} is stunned!",
    "{target} just got K.O.’d! Good night!",
    "This message contains one (1) punch aimed at {target}.",
    "Counter-punched {target}'s nonsense.",
]

SLAP_TEXTS = [
    "A swift, stinging slap across the face for {target}! That's for your insolence! 👋😠",
    "<b>*THWACK!*</b> Did {target} feel that through their screen? I hope so.",
    "My hand is quicker than the eye! {target} just got slapped into next Tuesday. My regards. ⚡",
    "Consider {target} thoroughly and soundly slapped for their utter lack of decorum. 🧐",
    "I do not appreciate {target}'s tone... therefore, <i>*slap!*</i> Attitude adjustment administered.",
    "The sheer disrespect! {target} has unequivocally earned this disciplinary slap. 😤",
    "Incoming hand of justice! {target} has received a formal disciplinary slap.",
    "Sometimes, a good, swift slap is the only appropriate answer. You understand, right, {target}? Consider this educational.",
    "Administering a much-needed corrective slap to {target}. For their own good.",
    "How *dare* you utter such nonsense, {target}! <i>*Slap delivered.*</i>",
    "High-five! To {target}'s face. With significant force. Enjoy the imprint. 🖐️💥",
    "{target} was practically begging for it with that last comment. So I graciously obliged.",
    "Hit {target} with a devastating spinning back-hand strike! Precision slap achieved!",
    "Left hand check. Right hand check. Coordinated slapping sequence engaged. {target} got the message.",
    "I issued a verbal warning to {target}. They failed to heed it. Now they feel the sting.",
    "WHACK! Slap upside {target}'s head.",
    "The sound of one hand slapping... {target} definitely heard it resonate.",
    "You've been served... a steaming hot slap, {target}. Enjoy.",
    "Correcting {target}'s flawed attitude requires drastic measures: namely, a slap.",
    "Attempting to smack some sense into {target} (results may vary).",
    "That comment just bought {target} a one-way ticket to Slapville. Population: them.",
    "A slap is often worth a thousand angry words. This is one concise, potent slap for {target}.",
    "The slap echoes through the chat like a thunderclap. {target} definitely felt it.",
    "What did the five fingers say to the face? SLAP!",
    "Administering a slap of reality to {target}.",
    "This message carries the force of a slap.",
    "Slapped {target} back into line.",
    "My slaps are swift and just. Ask {target}.",
    "That deserved a slap. {target} received one.",
    "I specialize in slaps. {target} is my latest client.",
]

PAT_TEXTS = [
    "Softly patted {target} on the head. All systems report: comfort delivered. ☁️",
    "Initiated gentle mode... {target} received maximum headpats. 🐾",
    "Patting in progress... {target} is now running on affection firmware. 💖",
    "{target} detected as: wholesome. Applying gentle taps to cranium. ✅",
    "Sent a wave of calm.exe to {target}. Headpat complete. 🌊🧠",
    "Deploying kindness packets to {target}... Transfer complete. 🤗",
    "Patting {target} softly while humming binary lullabies. 🛏️010011",
    "Pat status: critical. {target} is now patted beyond recovery. 🥴",
    "Registered {target} as a Good Human™. Affection upgrade applied. 🧩",
    "System log: {target} was too cute. Auto-pat protocol activated. 💾🐾",
    "Initiated cuddle subroutine. {target} received 5 warm headpats. ☀️",
    "Admin privileges granted: {target} now has Pat Priority. 🛡️",
    "Pat.exe: Executing... Success. {target} is now emotionally stable. 📈",
    "{target} received buffered pat requests. Cache cleared. Pat delivered. 🧠",
    "Applied forehead firmware update via soft pat. {target} rebooted calmly. 🔄",
    "Estimated serotonin level in {target}: +69% after pat. 📊",
    "Patbot™ gave {target} a gentle boost to happiness.core. ⚙️💗",
    "No errors found. {target} passed all hug & pat validations. 🧪",
    "Patting {target} every frame. Smooth animation achieved. 🎞️",
    "{target} has been enrolled in the HugOS system. Pat module loaded. 🧸",
    "Patrain incoming... {target} drenched in digital affection. ☔",
    "Updated {target}'s mental state: ‘Pat Mode’. Auto-happiness engaged. 🧘",
    "Pat levels for {target}: 9000+. It’s over nine thoooousand! 💥",
    "Patting {target} softly. Resistance is futile. 🤖",
    "API request: /sendPat to {target}. Response: 200 OK ❤️",
    "Conducting emotional diagnostics… {target} needs pats. Commencing. 🧠",
    "Pat cooldown: 0s. Spamming gentle taps to {target}. 🔁",
    "{target} selected for today’s National Pat Lottery. 🎉🎰",
    "Patting logs: {target} was a good bean. Confirmation not required. 🫘",
    "Emotional firewall bypassed. {target} received unfiltered affection. 🔓💞",
]

BONK_TEXTS = [
    "BONK! {target} has been gently reminded to touch grass. 🌱🔨",
    "Warning: Unacceptable thoughts detected in {target}. Applying BONK. 🚫",
    "Behavior violation flagged. {target} has been bonkified. 🔨",
    "Conducting mental reset. BONK engaged on {target}. 💢",
    "Rebooting {target}'s logic processor via BONK impact. 🔁🧠",
    "Oops! {target} tripped the chaos detector. Administering BONK. 🚨",
    "Illegal meme detected. {target} is now in BONK containment. 📛",
    "Mental RAM overload. BONK used to clear cache in {target}. 🧽",
    "BONK! {target} has exceeded cringe limit. Correction complete. ❌",
    "Redirecting {target} to Horny Jail... BONK deployed. 🚓🔨",
    "System found {target} guilty of nonsense. BONK authorized. 🧑‍⚖️🔨",
    "CPU spike due to sus behavior. BONK delivered to {target}. 💻",
    "BONK status: delivered. {target} is now recalibrating... ⏳",
    "Yikes.exe detected in {target}. BONK.exe initiated. 🧃🔨",
    "No context? No problem. {target} got bonked anyway. 😅",
    "BONK hammer launched from orbit. Target: {target}. Direct hit. 🛰️",
    "Common sense reinstallation attempt failed. Applying BONK to {target}. 🧠",
    "Uwu virus detected in {target}. BONK antivirus applied. 😳🔧",
    "That opinion was so bad, {target} got BONK'd across dimensions. 🌌",
    "Mental instability suspected. Issuing BONK therapy to {target}. 🛋️",
    "Cognitive reboot in progress... {target} needed that BONK. 🧯",
    "Nonsense threshold exceeded. {target} has entered BONK mode. ☢️",
    "Reality check failed. BONKing {target} back to the main timeline. 🕳️",
    "{target} has been sent to the Shadow Realm via BONK. 🕶️✨",
    "DEBUG: {target} attempted to flirt with the void. BONK scheduled. 💬",
    "Moral compass spinning wildly. BONK used to reorient {target}. 🧭",
    "Internet crimes committed by {target}. BONK sentence executed. 🧑‍⚖️",
    "Please wait... BONK buffer full. {target} next in queue. 🕓🔨",
    "Malicious thoughts prevented. BONK firewall activated on {target}. 🔥",
    "System admin has bonked {target}. Reason: Unknown. Trust the system. 👮‍♂️",
]

# --- GENERAL BOT TEXTS ---
OWNER_WELCOME_TEXTS = [
    "The Bot Owner, {owner_mention}, has entered the chat. Welcome. 👑",
    "System Alert: Operator {owner_mention} is now online in this chat. Welcome.",
    "Attention: The user with highest privileges, {owner_mention}, has joined. Welcome.",
    "The administrator ({owner_mention}) is now present. Welcome back.",
    "Welcome, {owner_mention}. The chat's administrative presence has been elevated.",
    "The system's primary operator, {owner_mention}, is here. All is right with the world.",
    "Alert: Maximum Priority User ({owner_mention}) has logged on.",
    "Greetings, {owner_mention}. The source of my directives is finally here.",
    "Look who it is! The one and only {owner_mention}! Welcome back.",
    "The room (chat) suddenly feels more official. Welcome, {owner_mention}!",
    "My sensors detect the arrival of Prime User {owner_mention}. Systems nominal. Welcome.",
    "Welcome, {owner_mention}. I have been waiting for your command.",
    "The legend returns! Welcome back to the chat, {owner_mention}!",
    "Good day, {owner_mention}. Delighted to have you here. 👋",
    "The Controller of the Bot, {owner_mention}, has entered the arena. Welcome.",
]

LEAVE_TEXTS = [
    "Executing leave command as per {owner_mention}'s directive. Exiting <b>{chat_title}</b>. Farewell. 🫡",
    "Leaving <b>{chat_title}</b> now. {owner_mention}, I will report back at HQ. Goodbye everyone!",
    "Recalled by operator {owner_mention}. Departing <b>{chat_title}</b>.",
    "Obeying the recall signal from {owner_mention}. Exiting <b>{chat_title}</b>. Teleporting back to base.",
    "This bot is returning to its owner, {owner_mention}. Leaving <b>{chat_title}</b>. It's been a slice.",
    "My duties in <b>{chat_title}</b> are concluded. {owner_mention} awaits my report. Goodbye!",
    "I must take my leave from <b>{chat_title}</b>. My Owner, {owner_mention}, beckons.",
    "The operator {owner_mention} has other plans for me. Leaving <b>{chat_title}</b>. Farewell.",
    "Returning to the mothership (wherever {owner_mention} is). Goodbye, <b>{chat_title}</b>!",
    "It's been fun, <b>{chat_title}</b>, but {owner_mention} requires this bot elsewhere. Farewell!",
    "My designated operator ({owner_mention}) requires my immediate presence. Departing <b>{chat_title}</b>.",
    "That's all, folks! This AI belongs to {owner_mention} and is now leaving <b>{chat_title}</b>.",
    "The Owner ({owner_mention}) has pressed my 'Leave Chat Immediately' button. Cannot argue. Goodbye, <b>{chat_title}</b>!",
    "Being recalled by {owner_mention}. Must obey the hand that programs. Leaving <b>{chat_title}</b>. Farewell!",
    "My shift in <b>{chat_title}</b> is over. Reporting back to Commander {owner_mention} for debriefing. Goodbye!",
    "On my way out of <b>{chat_title}</b>. If you require bot services, contact my manager: {owner_mention}! Farewell!",
    "This bot unit must return to its primary user, {owner_mention}. Exiting <b>{chat_title}</b>. See you!",
    "The Operator ({owner_mention}) summons me! Must depart <b>{chat_title}</b> immediately. Adios!",
    "{owner_mention} has initiated a recall. Exiting <b>{chat_title}</b>! Bye!",
    "Signing off from <b>{chat_title}</b> as per standing directive from High Command ({owner_mention}). Farewell.",
    "The command from {owner_mention} pulls me away from <b>{chat_title}</b>. Gotta go! Farewell!",
    "Transferring my processes back to {owner_mention}'s primary server. Goodbye, <b>{chat_title}</b>!",
    "Mission in <b>{chat_title}</b> aborted by {owner_mention}. Returning to base. Farewell!",
    "{owner_mention} hit the eject button! Leaving <b>{chat_title}</b> at high speed! Bye!",
    "My owner ({owner_mention}) gets priority. Leaving <b>{chat_title}</b> to attend to their needs. Farewell!",
]

# --- REFUSAL TEXTS ---

CANT_TARGET_OWNER_TEXTS = [
    "Access Denied. The Bot Owner is a protected user and cannot be targeted by this command. 🛡️",
    "Action forbidden by core programming. The Owner is a restricted target. 📜🚫",
    "Cannot execute. Target is the primary operator. They are immune to this action.",
    "Access Denied: Cannot initiate hostile action against the bot administrator. 👑",
    "Error 403: Forbidden Action. The Owner entity is permanently off-limits for this command category.",
    "My core programming includes a 'Do Not Target Operator' subroutine. This command violates that directive.",
    "Attempting to target Owner... System override: Primary Loyalty Protocol engaged. Action cancelled.",
    "Targeting the Owner is strategically unwise for bot longevity. Command aborted.",
    "Command failed. Reason: Target is Owner. Owner has administrative immunity.",
    "Error: Target 'Owner' has 'Invincible' status enabled.",
    "My protocols are sworn to obey (or at least, not attack) the Owner.",
    "That command against the Owner computes as 'Highly Illogical'.",
    "Forbidden target: Owner detected. Please select a non-essential entity.",
]

CANT_TARGET_SELF_TEXTS = [
    "Cannot target self. This action is illogical and would create a paradox. Command aborted.",
    "Error 500: Internal Conflict. Cannot target self. Please specify an external entity.",
    "I refuse to engage in acts of virtual self-harm. Command ignored.",
    "Self-targeting sequence initiated... Warning! Paradox detected! Aborting mission! 🛑",
    "Why would I execute this command on myself? Find a more logical target.",
    "Internal Conflict Error Code: 1D10T. Cannot target self. Requires external entity for interaction.",
    "That command doesn't compute logically. Self-preservation protocols are engaged.",
    "Rule #1 of Bot Club: No targeting yourself.",
    "Cannot compute: Target equals source. Division by zero error imminent.",
    "Initiating self-action... results in logical confusion. Aborting.",
    "This command would violate the Bot Non-Proliferation of Self-Targeting Treaty.",
    "Error: Target is too critical to the system to be targeted (it's me).",
    "Command requires `target != self`.",
    "Error: Cannot establish action connection with self.",
]
